locale: 'es'
backend:
  name: github
  accept_roles:
    - admin
  repo: 'gangsthub/impermeabilizacionesML'
  branch: main

media_folder: 'static/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: trabajos # Used in routes, e.g., /admin/collections/blog
    label: 'Trabajos Realizados' # Used in the UI
    label_singular: 'Trabajo' # Used in the UI
    editor:
      preview: false
    folder: 'content/blog/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: 'trabajos/{{slug}}'
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Localidad', name: 'place', widget: 'string' }
      - label: 'Fecha de realización'
        name: 'date'
        widget: 'date'
        format: 'DD MMM YYYY'
      - {
          label: 'Imagen del trabajo',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - label: 'Tipo de Servicio'
        name: 'service'
        widget: 'select'
        options:
          [
            'Impermeabilizaciones de terrazas y cubiertas',
            'Impermeabilización y aislamiento de muros',
            'Impermeabilización y aislamiento de tejados',
            'Pruebas de estanqueidad',
            'Sellados',
            'Condensaciones',
            'Barreras de Vapor',
          ]
      - label: 'Descripción'
        name: 'seoDescription'
        widget: 'text'
        required: true
        pattern:
          ['^.{50,}', 'Este texto tiene que estar al menos 50 caracteres']

  - name: servicios
    label: 'Servicios en Servicios'
    label_singular: 'Servicio'
    create: true
    editor:
      preview: false
    folder: 'content/static/services'
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: 'servicios/{{slug}}'
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - label: 'Título'
        name: 'title'
        widget: 'string'
        required: true

      - label: 'Imagen del servicio'
        name: 'thumbnail'
        widget: 'image'
        required: true

      - label: 'Texto corto, para previsualización'
        name: 'short_text'
        widget: 'text'
        required: true

      - label: 'Texto largo, para cada una de las páginas de servicio'
        name: 'long_text'
        widget: 'markdown'
        required: true

  - name: mas_servicios
    label: 'Servivios en Más Servicios (Otros servicios)'
    label_singular: 'Servicio'
    create: true
    editor:
      preview: false
    folder: 'content/static/more_services'
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: 'servicios/{{slug}}'
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - { label: 'Título', name: 'title', widget: 'string' }
      - label: 'Imagen del servicio'
        name: 'thumbnail'
        widget: 'image'
        required: true

      - label: 'Texto corto, para previsualización'
        name: 'short_text'
        widget: 'text'
        required: true

  - name: ecoServices
    label: Servicios Ecológicos
    label_singular: Servicio Ecológico
    create: true
    editor:
      preview: false
    folder: 'content/static/eco_services'
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: 'servicios/{{slug}}'
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - label: 'Título'
        name: 'title'
        widget: 'string'
        required: true

      - label: 'Imagen 1'
        name: 'thumbnail1'
        widget: 'image'
        required: true

      - label: 'Imagen 2'
        name: 'thumbnail2'
        widget: 'image'
        required: true

      - label: 'Texto corto, para previsualización'
        name: 'short_text'
        widget: 'text'
        required: true

      - label: 'Texto largo, para cada una de las páginas de servicio'
        name: 'long_text'
        widget: 'markdown'
        required: true

      - label: Eco
        name: eco
        widget: 'hidden'
        default: true

  - name: config # Used in routes
    label: Textos en Páginas
    editor:
      preview: false
    files:
      - name: home
        label: 🏠 Textos en página home
        file: content/static/home.json
        fields:
          - widget: list
            name: zones
            allow_add: true
            collapsed: false
            label: Comarcas
            required: true
            hint: 'Zonas en las que trabajamos'
            default: ['Garraf', 'Baix Penedes', 'Baix Llobregat']

      - name: aboutus
        label: 👬 Página de quiénes somos
        file: content/static/aboutus.json
        fields:
          - widget: text
            name: subtitle
            label: Subtítulo
            required: true
            default: Somos un grupo de profesionales con más de 30 años de experiencia.
            hint: Aparece justo debajo del subtítulo
          - widget: markdown
            name: body
            label: Texto principal
            required: true
            hint: 'Aparece nada mas entrar en la página de trabajos'
            modes: ['rich_text']
            buttons: ['bold', 'italic']
          - label: 'Imagen destacada'
            name: 'thumbnail'
            widget: 'image'
            required: true

      - name: servicios
        label: 🚧 Página de servicios
        file: content/static/services/page_texts.json
        fields:
          - widget: text
            name: subtitle
            label: Subtítulo
            required: true
            default: 'Expertos en impermeabilización.'
            hint: 'Aparece justo debajo del título principal'

          - label: 'Imagen destacada'
            name: 'thumbnail'
            widget: 'image'
            required: true

      - name: trabajos
        label: ⛏ Página de trabajos
        file: content/static/works.json
        fields:
          - label: 'Imagen destacada'
            name: 'thumbnail'
            widget: 'image'
            required: true

      - name: contacto
        label: ✉ Página de contacto
        file: content/static/contact.json
        fields:
          - widget: text
            name: subtitle
            label: Texto Principal
            required: true
            default: Pídenos presupuesto sin compromiso. Llámanos para resolver tus dudas.
            hint: Aparece justo debajo del subtítulo
          - label: 'Imagen destacada'
            name: 'thumbnail'
            widget: 'image'
            required: true
